import type { ContactData } from "@/lib/types"

export const contactsData: ContactData[] = [
  {
    id: "1",
    name: "Barkha Gupta",
    title: "Software Engineer",
    company: "Decimal Technologies",
    website: "decimaltech.com",
    companyEmail: "barkha.gupta@decimaltech.com",
    industry: "Information Technology",
    location: "Delhi, IN",
    companyLocation: "Gurugram, IN",
    employeeSize: "501 - 1,000 employees",
    seniority: "Mid-Level",
    department: "IT",
    dateResearched: "3 minutes ago",
  },
  {
    id: "2",
    name: "Rahul Sharma",
    title: "Senior Developer",
    company: "TechSolutions Inc",
    website: "techsolutions.com",
    companyEmail: "rahul.sharma@techsolutions.com",
    industry: "Information Technology",
    location: "Bangalore, IN",
    companyLocation: "Bangalore, IN",
    employeeSize: "201 - 500 employees",
    seniority: "Senior",
    department: "Engineering",
    dateResearched: "1 day ago",
  },
  {
    id: "3",
    name: "Priya Patel",
    title: "Marketing Manager",
    company: "Global Marketing Solutions",
    website: "globalmarketing.com",
    companyEmail: "priya.patel@globalmarketing.com",
    industry: "Marketing and Advertising",
    location: "Mumbai, IN",
    companyLocation: "Mumbai, IN",
    employeeSize: "51 - 200 employees",
    seniority: "Mid-Level",
    department: "Marketing",
    dateResearched: "2 days ago",
  },
]

